### ISSUE TITLE
Calendar error on ecFlow

### ISSUE THREAD

**Issue by AugustinMortier** [AugustinMortier/a-profiles#11]
An error related to the *map* json file is raised when processing *2022-01-30* with the CLI on ecFlow.

```
++TASK++ | start | 2022-01-31T01:21:01Z | /aqops/vprofiles/vp_run_yesterday
source ~/virtualenvs/vprofiles-centos7/bin/activate; python /home/charlien/A-Profiles/cli/aprocess.py --basedir-in /lustre/storeB/project/fou/kl/ceilometer/e-profile --basedir-out /lustre/storeB/project/fou/kl/v-profiles --date 2022-01-30 --multiprocessing
2022-01-30:   0%|          | 0/400 [00:00<?, ?it/s]2022-01-30:   0%|          | 1/400 [00:00<03:43,  1.78it/s]2022-01-30:   1%|          | 4/400 [00:00<00:54,  7.22it/s]/home/charlien/A-Profiles/cli/utils/workflow.py:14: UserWarning: Error with /lustre/storeB/project/fou/kl/ceilometer/e-profile/2022/01/30/L2_0-20008-0BRC_A20220130.nc. attenuated_backscatter_0 variable has 112896/188640 values as NaNs.
  warnings.warn(f"Error with {path}. attenuated_backscatter_0 variable has {nans}/{total} values as NaNs.")
……….
……..
Traceback (most recent call last):
  File "/home/charlien/A-Profiles/cli/aprocess.py", line 129, in <module>
    typer.run(main)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/typer/main.py", line 864, in run
    app()
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/charlien/A-Profiles/cli/aprocess.py", line 125, in main
    utils.json_map.add_to_map(file, basedir_out, yyyy, mm, dd, mapname)
  File "/home/charlien/A-Profiles/cli/utils/json_map.py", line 52, in add_to_map
    data = json.load(json_file)
  File "/modules/centos7/python/Python-3.8.7/Lib/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/modules/centos7/python/Python-3.8.7/Lib/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/modules/centos7/python/Python-3.8.7/Lib/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/modules/centos7/python/Python-3.8.7/Lib/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

@charlienegri I tried processing the date locally with 
`cli/aprocess.py --date 2022-01-30 --multiprocessing` but did not get any issue.
I also reprocessed the map after downloading the map json file on *data_tmp* from the web server, so it would use this existing file, but once again, no error.
I also tried running explicitly *yesterday*
`cli/aprocess.py --yesterday --multiprocessing --no-update-data` and that worked as well.

Some things I have in mind that we could do to investigate the error source:
- [ ] try reprocessing this day after deleting the map json file
- [ ] try using *python3.9* instead of *python3.8*

**Comment by charlienegri** [comment]
I re-run the 'yesterday' job now in ecflow and it went through.... I have no idea why. I will try to dig deeper.

**Comment by charlienegri** [comment]
also, on the 27th a similar error happened, but at the calendar processing, so it has nothing to do with the map specifically:
```
##### START /aqops/vprofiles/vp_run @ 2022-01-27T08:51:01Z with 105151 #####

2022/01/27 08:51:01 Jobhost: c6320-6f08lg2-ag-compute.int.met.no
2022/01/27 08:51:01 Jobhost OS release (OS_RELEASE): Core
2022/01/27 08:51:01 ecflow-server (ECF_HOST):  ppi-blogin-a1
2022/01/27 08:51:01 ulimit -a: core file size          (blocks, -c) 0, data seg size           (kbytes, -d) unlimited, scheduling priority             (-e) 0, file size               (blocks, -f) unlimited, pending signals                 (-i) 1030570, max locked memory       (kbytes, -l) 4194304, max memory size         (kbytes, -m) unlimited, open files                      (-n) 16384, pipe size            (512 bytes, -p) 8, POSIX message queues     (bytes, -q) 819200, real-time priority              (-r) 0, stack size              (kbytes, -s) unlimited, cpu time               (seconds, -t) unlimited, max user processes              (-u) 16384, virtual memory          (kbytes, -v) 41943040, file locks                      (-x) unlimited,
2022/01/27 08:51:01 Using runtime environment variables from: /home/charlien/ecflow_playground/etc/runtime-env-c6220ii-d12b002-ar-compute.int.met.no
2022/01/27 08:51:01 PATH: /home/charlien/.poetry/bin:/home/charlien/.local/bin:/usr/share/Modules/bin:/tmp/4293302.1.research-el7.q:/modules/bionic/user-apps/metprod-ecflow/production/bin:/bin:/usr/bin:/sbin:/usr/sbin:/home/charlien/ecflow_playground/ecflowsuite-aqops/bin:/home/charlien/ecflow_playground/ecflowsuite-aqops/vprofiles/bin:/usr/local/sbin:/opt/dell/srvadmin/bin
2022/01/27 08:51:01 MET_ECFLOW_PRODHOME: /home/charlien/ecflow_playground
2022/01/27 08:51:01 MET_IS_MAIN_SERVER: 0
2022/01/27 08:51:01 ECF_ENVIRONMENT: devel
2022/01/27 08:51:01 MET_ETCDIR: /home/charlien/ecflow_playground/ecflowsuite-aqops/vprofiles/etc
2022/01/27 08:51:01 MET_LIBDIR: /home/charlien/ecflow_playground/ecflowsuite-aqops/vprofiles/lib
2022/01/27 08:51:01 MET_BINDIR: /home/charlien/ecflow_playground/ecflowsuite-aqops/vprofiles/bin
2022/01/27 08:51:01 MET_WORKDIR: /lustre/storeA/users/charlien/ecflowdata/work/vprofiles
2022/01/27 08:51:01 MET_PRODUCTION_DIR: /lustre/storeA/users/charlien/ecflowdata
2022/01/27 08:51:01 MET_DATADIR: /lustre/storeA/users/charlien/ecflowdata/products/vprofiles
2022/01/27 08:51:01 TASK_TIMEOUT: 180 min.
2022/01/27 08:51:01 ECF_TRIES: 3
2022/01/27 08:51:01 ECF_TRYNO: 1
2022/01/27 08:51:01 GRIDENGINE JOB_ID: 4293302
++TASK++ | start | 2022-01-27T08:51:01Z | /aqops/vprofiles/vp_run
source ~/virtualenvs/vprofiles-centos7/bin/activate; python /home/charlien/A-Profiles/cli/aprocess.py --basedir-in /lustre/storeA/project/fou/kl/ceilometer/e-profile --basedir-out /lustre/storeA/project/fou/kl/v-profiles --date 2022-01-27 --multiprocessing
2022-01-27:   0%|          | 0/401 [00:00<?, ?it/s]2022-01-27:   0%|          | 1/401 [00:00<02:15,  2.96it/s]2022-01-27:   6%|▋         | 26/401 [00:00<00:04, 75.83it/s]2022-01-27:  12%|█▏        | 49/401 [00:00<00:02, 120.64it/s]2022-01-27:  17%|█▋        | 68/401 [00:00<00:02, 124.96it/s]2022-01-27:  21%|██        | 85/401 [00:00<00:02, 109.95it/s]/home/charlien/A-Profiles/cli/utils/workflow.py:14: UserWarning: Error with /lustre/storeA/project/fou/kl/ceilometer/e-profile/2022/01/27/L2_0-20008-0BRC_A20220127.nc. attenuated_backscatter_0 variable has 37240/62225 values as NaNs.
  warnings.warn(f"Error with {path}. attenuated_backscatter_0 variable has {nans}/{total} values as NaNs.")
2022-01-27:  25%|██▍       | 99/401 [00:01<00:04, 67.67it/s] 2022-01-27:  27%|██▋       | 110/401 [00:08<00:50,  5.73it/s]2022-01-27:  29%|██▉       | 117/401 [00:09<00:44,  6.33it/s]2022-01-27:  31%|███       | 123/401 [00:10<00:43,  6.43it/s]2022-01-27:  32%|███▏      | 127/401 [00:10<00:39,  6.97it/s]2022-01-27:  32%|███▏      | 130/401 [00:10<00:35,  7.63it/s]2022-01-27:  33%|███▎      | 133/401 [00:10<00:32,  8.18it/s]2022-01-27:  34%|███▍      | 136/401 [00:11<00:31,  8.47it/s]2022-01-27:  34%|███▍      | 138/401 [00:11<00:32,  8.12it/s]2022-01-27:  35%|███▍      | 140/401 [00:11<00:34,  7.54it/s]2022-01-27:  35%|███▌      | 142/401 [00:12<00:55,  4.70it/s]2022-01-27:  36%|███▌      | 143/401 [00:12<00:51,  5.01it/s]2022-01-27:  36%|███▌      | 145/401 [00:13<00:44,  5.75it/s]2022-01-27:  37%|███▋      | 147/401 [00:13<00:37,  6.80it/s]2022-01-27:  37%|
 ███▋      | 149/401 [00:13<00:31,  7.93it/s]2022-01-27:  38%|███▊      | 151/401 [00:13<00:30,  8.33it/s]2022-01-27:  38%|███▊      | 153/401 [00:13<00:24,  9.93it/s]2022-01-27:  39%|███▉      | 157/401 [00:13<00:18, 13.02it/s]2022-01-27:  40%|████      | 161/401 [00:14<00:17, 13.54it/s]2022-01-27:  41%|████      | 164/401 [00:14<00:17, 13.76it/s]2022-01-27:  41%|████▏     | 166/401 [00:14<00:16, 14.11it/s]2022-01-27:  42%|████▏     | 168/401 [00:14<00:19, 12.07it/s]2022-01-27:  42%|████▏     | 170/401 [00:14<00:19, 12.03it/s]2022-01-27:  43%|████▎     | 172/401 [00:15<00:17, 12.79it/s]2022-01-27:  43%|████▎     | 174/401 [00:15<00:19, 11.85it/s]2022-01-27:  44%|████▍     | 176/401 [00:15<00:20, 10.95it/s]2022-01-27:  44%|████▍     | 178/401 [00:15<00:19, 11.73it/s]2022-01-27:  45%|████▍     | 180/401 [00:15<00:21, 10.48it/s]2022-01-27
 :  45%|████▌     | 182/401 [00:16<00:27,  7.88it/s]2022-01-27:  46%|████▌     | 183/401 [00:16<00:29,  7.33it/s]2022-01-27:  46%|████▌     | 184/401 [00:16<00:30,  7.20it/s]2022-01-27:  46%|████▌     | 185/401 [00:16<00:29,  7.34it/s]2022-01-27:  47%|████▋     | 187/401 [00:16<00:24,  8.65it/s]2022-01-27:  47%|████▋     | 189/401 [00:17<00:45,  4.69it/s]2022-01-27:  47%|████▋     | 190/401 [00:18<01:07,  3.13it/s]2022-01-27:  48%|████▊     | 191/401 [00:18<00:59,  3.54it/s]2022-01-27:  48%|████▊     | 192/401 [00:18<00:51,  4.05it/s]2022-01-27:  48%|████▊     | 193/401 [00:18<00:46,  4.47it/s]2022-01-27:  49%|████▊     | 195/401 [00:19<00:31,  6.62it/s]2022-01-27:  49%|████▉     | 197/401 [00:19<00:23,  8.71it/s]2022-01-27:  50%|████▉     | 199/401 [00:19<00:21,  9.59it/s]2022-01-27:  50%|█████     | 201/401 [00:19<00:20,  9
 .57it/s]2022-01-27:  51%|█████     | 204/401 [00:19<00:14, 13.20it/s]2022-01-27:  51%|█████▏    | 206/401 [00:19<00:14, 13.05it/s]2022-01-27:  52%|█████▏    | 208/401 [00:19<00:15, 12.12it/s]2022-01-27:  53%|█████▎    | 211/401 [00:20<00:12, 15.63it/s]2022-01-27:  53%|█████▎    | 213/401 [00:20<00:13, 14.37it/s]2022-01-27:  54%|█████▎    | 215/401 [00:20<00:13, 13.45it/s]2022-01-27:  54%|█████▍    | 217/401 [00:20<00:13, 13.51it/s]2022-01-27:  55%|█████▍    | 219/401 [00:21<00:22,  7.93it/s]2022-01-27:  55%|█████▌    | 221/401 [00:21<00:24,  7.32it/s]2022-01-27:  55%|█████▌    | 222/401 [00:21<00:37,  4.77it/s]2022-01-27:  56%|█████▌    | 223/401 [00:22<00:34,  5.13it/s]2022-01-27:  56%|█████▌    | 225/401 [00:22<00:44,  3.93it/s]2022-01-27:  56%|█████▋    | 226/401 [00:24<01:40,  1.74it/s]2022-01-27:  57%|█
 ████▋    | 227/401 [00:24<01:24,  2.07it/s]2022-01-27:  57%|█████▋    | 228/401 [00:25<01:36,  1.79it/s]2022-01-27:  57%|█████▋    | 229/401 [00:25<01:19,  2.16it/s]2022-01-27:  57%|█████▋    | 230/401 [00:26<01:19,  2.16it/s]2022-01-27:  58%|█████▊    | 231/401 [00:26<01:10,  2.40it/s]2022-01-27:  58%|█████▊    | 232/401 [00:26<00:58,  2.89it/s]2022-01-27:  58%|█████▊    | 234/401 [00:26<00:39,  4.22it/s]2022-01-27:  59%|█████▊    | 235/401 [00:27<00:35,  4.69it/s]2022-01-27:  59%|█████▉    | 236/401 [00:27<00:31,  5.31it/s]2022-01-27:  59%|█████▉    | 238/401 [00:27<00:25,  6.32it/s]2022-01-27:  60%|██████    | 241/401 [00:27<00:18,  8.86it/s]2022-01-27:  60%|██████    | 242/401 [00:27<00:19,  8.34it/s]2022-01-27:  61%|██████    | 243/401 [00:27<00:19,  8.27it/s]2022-01-27:  61%|██████    | 244/40
 1 [00:28<00:21,  7.29it/s]2022-01-27:  61%|██████    | 245/401 [00:28<00:24,  6.38it/s]2022-01-27:  61%|██████▏   | 246/401 [00:29<01:24,  1.84it/s]2022-01-27:  62%|██████▏   | 247/401 [00:30<01:06,  2.31it/s]2022-01-27:  62%|██████▏   | 248/401 [00:30<01:03,  2.40it/s]2022-01-27:  62%|██████▏   | 249/401 [00:30<01:09,  2.20it/s]2022-01-27:  63%|██████▎   | 251/401 [00:31<00:45,  3.30it/s]2022-01-27:  63%|██████▎   | 252/401 [00:31<00:46,  3.18it/s]2022-01-27:  63%|██████▎   | 254/401 [00:31<00:32,  4.56it/s]2022-01-27:  64%|██████▍   | 256/401 [00:31<00:24,  5.94it/s]2022-01-27:  65%|██████▌   | 261/401 [00:32<00:14,  9.75it/s]2022-01-27:  66%|██████▋   | 266/401 [00:32<00:08, 15.14it/s]2022-01-27:  67%|██████▋   | 269/401 [00:32<00:07, 17.29it/s]2022-01-27:  69%|██████▊   | 275/401 [
 00:32<00:05, 21.63it/s]2022-01-27:  70%|██████▉   | 280/401 [00:32<00:05, 23.63it/s]2022-01-27:  71%|███████   | 283/401 [00:32<00:05, 19.80it/s]2022-01-27:  71%|███████▏  | 286/401 [00:33<00:07, 15.12it/s]2022-01-27:  72%|███████▏  | 288/401 [00:33<00:07, 15.42it/s]2022-01-27:  72%|███████▏  | 290/401 [00:33<00:07, 14.30it/s]2022-01-27:  73%|███████▎  | 294/401 [00:33<00:07, 14.99it/s]2022-01-27:  74%|███████▍  | 296/401 [00:33<00:06, 15.34it/s]2022-01-27:  75%|███████▍  | 299/401 [00:34<00:06, 16.32it/s]2022-01-27:  75%|███████▌  | 301/401 [00:34<00:06, 15.61it/s]2022-01-27:  76%|███████▌  | 303/401 [00:34<00:07, 13.90it/s]2022-01-27:  76%|███████▌  | 305/401 [00:35<00:23,  4.12it/s]2022-01-27:  77%|███████▋  | 307/401 [00:36<00:20,  4.61it/s]2022-01-27:  77%|█████â
 ��█▋  | 308/401 [00:36<00:27,  3.43it/s]2022-01-27:  77%|███████▋  | 309/401 [00:37<00:31,  2.91it/s]2022-01-27:  77%|███████▋  | 310/401 [00:37<00:34,  2.67it/s]2022-01-27:  78%|███████▊  | 311/401 [00:38<00:29,  3.06it/s]2022-01-27:  78%|███████▊  | 313/401 [00:38<00:21,  4.13it/s]2022-01-27:  79%|███████▊  | 315/401 [00:38<00:14,  5.75it/s]2022-01-27:  79%|███████▉  | 317/401 [00:38<00:11,  7.57it/s]2022-01-27:  80%|███████▉  | 319/401 [00:38<00:09,  9.11it/s]2022-01-27:  80%|████████  | 321/401 [00:38<00:08,  9.76it/s]2022-01-27:  81%|████████  | 323/401 [00:38<00:07, 10.85it/s]2022-01-27:  81%|████████  | 325/401 [00:39<00:07, 10.32it/s]2022-01-27:  82%|████████▏ | 327/401 [00:39<00:08,  8.37it/s]2022-01-27:  82%|████████▏ | 329/401 [00:39<00:08,  8.63it/s]2022
 -01-27:  83%|████████▎ | 331/401 [00:39<00:07,  9.78it/s]2022-01-27:  83%|████████▎ | 333/401 [00:40<00:07,  8.59it/s]2022-01-27:  84%|████████▎ | 335/401 [00:40<00:07,  9.38it/s]2022-01-27:  84%|████████▍ | 337/401 [00:40<00:06,  9.84it/s]2022-01-27:  85%|████████▍ | 339/401 [00:40<00:07,  8.78it/s]2022-01-27:  85%|████████▍ | 340/401 [00:41<00:07,  7.83it/s]2022-01-27:  85%|████████▌ | 341/401 [00:41<00:09,  6.56it/s]2022-01-27:  86%|████████▌ | 343/401 [00:41<00:07,  8.17it/s]2022-01-27:  86%|████████▌ | 344/401 [00:41<00:12,  4.68it/s]2022-01-27:  86%|████████▌ | 345/401 [00:42<00:11,  5.01it/s]2022-01-27:  86%|████████▋ | 346/401 [00:42<00:10,  5.45it/s]2022-01-27:  87%|████████▋ | 347/401 [00:42<00:09,  5.84it/s]2022-01-27:  87%|█████â
 ��██▋ | 348/401 [00:42<00:10,  4.87it/s]2022-01-27:  87%|████████▋ | 350/401 [00:42<00:08,  6.09it/s]2022-01-27:  88%|████████▊ | 351/401 [00:43<00:07,  6.68it/s]2022-01-27:  88%|████████▊ | 352/401 [00:43<00:07,  6.37it/s]2022-01-27:  88%|████████▊ | 353/401 [00:43<00:07,  6.11it/s]2022-01-27:  89%|████████▊ | 355/401 [00:43<00:05,  8.39it/s]2022-01-27:  89%|████████▉ | 356/401 [00:43<00:06,  7.25it/s]2022-01-27:  89%|████████▉ | 357/401 [00:45<00:23,  1.84it/s]2022-01-27:  89%|████████▉ | 358/401 [00:46<00:25,  1.71it/s]2022-01-27:  90%|████████▉ | 359/401 [00:46<00:19,  2.14it/s]2022-01-27:  90%|████████▉ | 360/401 [00:47<00:28,  1.45it/s]2022-01-27:  90%|█████████ | 361/401 [00:48<00:28,  1.42it/s]2022-01-27:  90%|█████████ | 362/401 [00:48<
 00:25,  1.53it/s]2022-01-27:  91%|█████████ | 363/401 [00:49<00:20,  1.82it/s]2022-01-27:  91%|█████████ | 364/401 [00:49<00:22,  1.62it/s]2022-01-27:  91%|█████████ | 365/401 [00:50<00:22,  1.57it/s]2022-01-27:  91%|█████████▏| 366/401 [00:51<00:21,  1.61it/s]2022-01-27:  92%|█████████▏| 368/401 [00:51<00:12,  2.63it/s]2022-01-27:  92%|█████████▏| 369/401 [00:51<00:11,  2.91it/s]2022-01-27:  93%|█████████▎| 371/401 [00:51<00:07,  3.92it/s]2022-01-27:  93%|█████████▎| 372/401 [00:52<00:10,  2.79it/s]2022-01-27:  93%|█████████▎| 373/401 [00:52<00:09,  2.91it/s]2022-01-27:  93%|█████████▎| 374/401 [00:53<00:14,  1.87it/s]2022-01-27:  94%|█████████▎| 375/401 [00:54<00:11,  2.30it/s]2022-01-27:  94%|█████████▍| 377/401 [00:54<00:06,  3.7
 2it/s]2022-01-27:  94%|█████████▍| 378/401 [00:54<00:08,  2.78it/s]2022-01-27:  95%|█████████▍| 379/401 [00:55<00:07,  3.12it/s]2022-01-27:  95%|█████████▍| 380/401 [00:55<00:09,  2.18it/s]2022-01-27:  95%|█████████▌| 382/401 [00:57<00:12,  1.56it/s]2022-01-27:  96%|█████████▌| 383/401 [00:58<00:11,  1.51it/s]2022-01-27:  96%|█████████▌| 384/401 [00:59<00:11,  1.43it/s]2022-01-27:  96%|█████████▌| 385/401 [01:00<00:12,  1.29it/s]2022-01-27:  97%|█████████▋| 387/401 [01:00<00:07,  1.89it/s]2022-01-27:  97%|█████████▋| 388/401 [01:00<00:06,  2.09it/s]2022-01-27:  97%|█████████▋| 389/401 [01:01<00:04,  2.56it/s]2022-01-27:  97%|█████████▋| 390/401 [01:01<00:04,  2.45it/s]2022-01-27:  98%|█████████▊| 392/401 [01:01<00:02,  3.04it/s
 ]2022-01-27:  98%|█████████▊| 394/401 [01:02<00:02,  3.47it/s]2022-01-27:  99%|█████████▉| 396/401 [01:03<00:02,  2.38it/s]2022-01-27:  99%|█████████▉| 397/401 [01:04<00:01,  2.02it/s]2022-01-27: 100%|█████████▉| 399/401 [01:04<00:00,  2.97it/s]2022-01-27: 100%|█████████▉| 400/401 [01:04<00:00,  3.18it/s]2022-01-27: 100%|██████████| 401/401 [01:05<00:00,  3.19it/s]2022-01-27: 100%|██████████| 401/401 [01:05<00:00,  6.14it/s]
calendar  :   0%|          | 0/133 [00:00<?, ?it/s]calendar  :   2%|▏         | 2/133 [00:00<00:14,  9.23it/s]calendar  :   3%|▎         | 4/133 [00:00<00:10, 12.73it/s]calendar  :   5%|▍         | 6/133 [00:00<00:08, 14.52it/s]calendar  :   6%|▌         | 8/133 [00:00<00:07, 15.66it/s]calendar  :   8%|▊         | 10/133 [00:00<00:07, 16.19it/s]calendar  :   9%|▉         | 12/133 [00:00<00:07, 16.67it/s]calendar  :  11%|█▏        | 15/133 [00:00<00:06, 18.28it/s]calendar  :  12%|█▏        | 16/133 [00:00<00:07, 16.31it/s]
Traceback (most recent call last):
  File "/home/charlien/A-Profiles/cli/aprocess.py", line 129, in <module>
    typer.run(main)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/typer/main.py", line 864, in run
    app()
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/charlien/A-Profiles/cli/aprocess.py", line 114, in main
    utils.json_calendar.add_to_calendar(file, basedir_out, yyyy, mm, dd, calname)
  File "/home/charlien/A-Profiles/cli/utils/json_calendar.py", line 26, in add_to_calendar
    scene_counts[scene_class] = len(ds.retrieval_scene.data[ds.retrieval_scene.data == scene_class])
  File "/home/charlien/virtualenvs/vprofiles-centos7/lib/python3.8/site-packages/xarray/core/common.py", line 246, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'retrieval_scene'

************************** MAIL_WARNING **********************
 -- /home/charlien/A-Profiles/cli/aprocess.py command exception:Command 'source ~/virtualenvs/vprofiles-centos7/bin/activate; python /home/charlien/A-Profiles/cli/aprocess.py --basedir-in /lustre/storeA/project/fou/kl/ceilometer/e-profile --basedir-out /lustre/storeA/project/fou/kl/v-profiles --date 2022-01-27 --multiprocessing' returned non-zero exit status 1.
************************************************************
```

**Comment by charlienegri** [comment]
got some more errors, posting here for reference:
-  ```json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)``` on the run at 2022-02-02T03:21:07Z
-  ```KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/lustre/storeB/project/fou/kl/v-profiles/2022/02/01/AP_0-20000-0-10379-0-2022-02-01.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]
``` at 2022-02-01T17:51:03Z
- ```AttributeError: 'Dataset' object has no attribute 'retrieval_scene'``` (with a warning at the start, might be related ```/home/charlien/A-Profiles/cli/utils/workflow.py:21: UserWarning: Error with /lustre/storeA/project/fou/kl/ceilometer/e-profile/2022/02/01/L2_0-20008-0BRC_A20220201.nc. attenuated_backscatter_0 variable has 79184/132310 values as NaNs.
  warnings.warn(f"Error with {path}. attenuated_backscatter_0 variable has {nans}/{total} values as NaNs.")
```)
full trace pasted [here](https://docs.google.com/document/d/1RpxGxpLbxFdWlXg1fikCwXqEj-1lQkwnVO97Pa54tT0/edit)
