### ISSUE TITLE
check order of coordinates in attenuated_backscatter_0 (in read_eprofile.py)

### ISSUE THREAD

**Issue by Joelle83** [AugustinMortier/A-Profiles#8]
When using CEDA archive data, e.g.
Camborne 4th August 2021
https://dap.ceda.ac.uk/badc/eprofile/data/daily_files/uk/camborne/metoffice-jenoptick-chm15k-nimbus_A/2021/L2_0-20000-0-03808_A20210804.nc

(concatenated data) the main.py will fail with following error message:
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(path)
  File "main.py", line 36, in main
    save_fig="docs/_static/images/QL-CA-20210909.png"
  File "/net/home/h01/jbuxmann/Aprofile/A-Profiles/aprofiles/profiles.py", line 464, in plot
    apro.plot.image.plot(self.data, var, zref, zmin, zmax, vmin, vmax, log, show_foc, show_pbl, show_clouds, cmap, show_fig, save_fig)
  File "/net/home/h01/jbuxmann/Aprofile/A-Profiles/aprofiles/plot/image.py", line 187, in plot
    shading="nearest",
  File "/net/home/h01/jbuxmann/vaprofile/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2804, in pcolormesh
    **({"data": data} if data is not None else {}), **kwargs)
  File "/net/home/h01/jbuxmann/vaprofile/lib/python3.6/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/net/home/h01/jbuxmann/vaprofile/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6093, in pcolormesh
    shading=shading, kwargs=kwargs)
  File "/net/home/h01/jbuxmann/vaprofile/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 5627, in _pcolorargs
    C.shape, Nx, Ny, funcname))
TypeError: Dimensions of C (261, 511) are incompatible with X (261) and/or Y (511); see help(pcolormesh)

Solution:
I added 
ds= ds.transpose(...,'altitude')
in L45 in read_eprofile.py
altitude and time have been in reverse (wrong) order in the CEDA file.
This way altitude will be last, better way would be to check the order of variables and only transpose if necessary.
However, still works with test data from Oslo provided.

**Comment by AugustinMortier** [comment]
Thanks a lot Joelle for your feedback.

I was surprised to know there was an issue with reading some station since I processed all CHM15k and Mini-MPL of E-PROFILE for two days, without any error. After verification, the data I'm reading in have been slightly mnodified as compared to the ones on the hub, with the following command (extracted from the netcdf history):

_history = "Wed Aug  4 00:30:39 2021: ncpdq -O -a time,altitude /data/temp/L2_0-20000-0-03808_A202108040000.nc /data/temp/L2_0-20000-0-03808_A202108040000.nc\n20210804 raw2l1 3.0.5 / 20210804 L12L2 2.0.1"_ 

knowing that the option '-a' of ncpdq is meant to reorder dimensions.

Then, it's indeed an easy fix, as we just have to make sure that the dimensions are in this prescribed order: time, altitude.
 
I'm pushing a quick fix very soon.

**Comment by AugustinMortier** [comment]
Fixed with dd606b83d42b8041f0bb4cee6f02a16e0d681bab
